export const API_URL = 'http://localhost:3001';
export const POST_COMMENT = "POST_COMMENT";
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const RECEIVE_DELETED_POSTS = "RECEIVE_DELETED_POSTS";
export const RECEIVE_POST = "RECEIVE_POST";
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const REQUEST_CATEGORIES = "REQUEST_CATEGORIES";
export const UPDATE_POST = "UPDATE_POST";
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const REQUEST_POST_DELETE = "REQUEST_POST_DELETE";
export const REQUEST_COMMENT_DELETE = "REQUEST_COMMENT_DELETE";
export const RECIEVE_COMMENT_DELETED = "RECIEVE_COMMENT_DELETED";
export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const REQUEST_POST = "REQUEST_POST";
export const REQUEST_POSTS_FOR_CATEGORY = "REQUEST_POSTS_FOR_CATEGORY";
export const REQUEST_POST_UPDATE = "REQUEST_POST_UPDATE";
export const REQUEST_POSTS = "REQUEST_POSTS";

export const sortDirections = {
    Ascending: 'asc',
    Descending: 'dsc'
};
